apiVersion: v1
kind: Service
metadata:
  name: numbers-api
spec:
  selector:
    app: lab-numbers-api
    version: v1
  ports:
    - port: 80
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: lab-numbers-web
spec:
  selector:
    app: lab-numbers-web
    version: v1
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
  
---

apiVersion: v1
kind: Service
metadata:
  name: lab-numbers-web-v2
spec:
  selector:
    app: lab-numbers-web
    version: v2
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30088
  type: NodePort
  